# Generated by Django 2.1 on 2019-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('avatar_url', models.CharField(max_length=200, null=True)),
                ('nick_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
