# Generated by Django 2.1 on 2019-09-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
