# Generated by Django 2.1 on 2019-09-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_alipay_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
