# Generated by Django 2.1 on 2019-09-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('out_trade_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('trade_no', models.CharField(max_length=100, null=True)),
                ('money', models.FloatField()),
                ('subject', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.User')),
            ],
        ),
    ]
